"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.customerCRUDService = void 0;
const db_1 = require("../../firebase/db");
const enum_1 = require("../../utils/enum");
const customer_service_1 = require("./customer.service");
const customer_entitie_1 = require("./entitie/customer.entitie");
const dbFirestore = new db_1.DbFirestore(enum_1.CollectionsName.customerColl);
const customerEntitie = new customer_entitie_1.CustomerEntitie();
const customerCRUDService = new customer_service_1.CustomerCRUDService(customerEntitie, dbFirestore);
exports.customerCRUDService = customerCRUDService;
