"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.brokerService = void 0;
const db_1 = require("../../firebase/db");
const enum_1 = require("../../utils/enum");
const customer_module_1 = require("../customer/customer.module");
const order_module_1 = require("../order/order.module");
const broker_service_1 = require("./broker.service");
const dbFirestore = new db_1.DbFirestore(enum_1.CollectionsName.chatControllerColl);
const brokerService = new broker_service_1.BrokerService(dbFirestore, customer_module_1.customerCRUDService, order_module_1.orderCRUDService);
exports.brokerService = brokerService;
